# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88fcd232e29c60aaf00effb49d9b530b3c21935f92b9fd9c452f2c97f7839ba7dbb08cf73879452e8e4aec24bd9fd5a05d3cb221051f92e02270b088c591dbe0

test:
  secret_key_base: 6ad044813196ee03e948816b721ccd2a05f5fde2072c39ecc76ac6c75724b65345140efdf429958cb49f384b1371c5ea4a3547e2c57398408c735c20f124b932

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
